import { Router } from 'express';
import { CharacterTemplate } from '../models/CharacterTemplate.js';
import { Character } from '../models/Character.js';

const router = Router();

function buildDefaultTemplate(template) {
  return {
    thumbnailUrl: '',
    isDefault: true,
    role: 'protagonist',
    ageRange: '',
    traits: [],
    tags: [],
    visualDNA: {
      style: 'pixar-3d',
      gender: '',
      ageLook: '',
      skinTone: '',
      eyeColor: '',
      faceShape: '',
      eyebrowStyle: '',
      noseStyle: '',
      cheekStyle: '',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: '',
      topGarmentColor: '',
      topGarmentDetails: '',
      bottomGarmentType: '',
      bottomGarmentColor: '',
      shoeType: '',
      shoeColor: '',
      bodyBuild: '',
      heightFeel: '',
      heightCm: 0,
      weightKg: 0,
      facialHair: '',
      glasses: '',
      accessories: [],
      paletteNotes: '',
      ...(template.visualDNA || {}),
    },
    modestyRules: {
      hijabAlways: false,
      longSleeves: false,
      looseClothing: true,
      notes: '',
      ...(template.modestyRules || {}),
    },
    palettePreview: {
      primary: '',
      secondary: '',
      accent: '',
      ...(template.palettePreview || {}),
    },
    ...template,
  };
}

const UNIVERSAL_DEFAULT_TEMPLATES = [
  buildDefaultTemplate({
    _id: 'default_john_magic_boathouse',
    name: 'John - Magic Boathouse',
    description: 'An adventurous boy with a striped raincoat and a pocket compass. Great for river journeys, mystery islands, and weathery adventures.',
    category: 'boy',
    tags: ['universal', 'boy', 'adventure', 'boat', 'explorer'],
    traits: ['adventurous', 'resourceful', 'brave'],
    ageRange: '8-11',
    visualDNA: {
      gender: 'boy',
      ageLook: '9-year-old',
      skinTone: 'peach',
      eyeColor: 'blue',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'soft-straight',
      noseStyle: 'small-straight',
      cheekStyle: 'light-freckles',
      hairStyle: 'wind-swept crop',
      hairColor: 'light-brown',
      topGarmentType: 'hooded raincoat over striped tee',
      topGarmentColor: 'sunny yellow',
      topGarmentDetails: 'brass compass clipped to zipper',
      bottomGarmentType: 'rolled adventure trousers',
      bottomGarmentColor: 'navy',
      shoeType: 'rubber boots',
      shoeColor: 'red',
      bodyBuild: 'slim and springy',
      heightFeel: 'average height',
      heightCm: 132,
      weightKg: 29,
      accessories: ['tiny compass', 'toy sailboat'],
      paletteNotes: 'Yellow, navy, red - bright storybook adventure',
    },
    palettePreview: { primary: '#FBC02D', secondary: '#1E3A8A', accent: '#E53935' },
  }),
  buildDefaultTemplate({
    _id: 'default_emma_puppy_day',
    name: 'Emma - Puppy Day',
    description: 'A cheerful girl hugging her scruffy puppy. Perfect for gentle home stories, neighborhood fun, and first responsibilities.',
    category: 'girl',
    tags: ['universal', 'girl', 'puppy', 'kind', 'home'],
    traits: ['kind', 'cheerful', 'responsible'],
    ageRange: '6-9',
    visualDNA: {
      gender: 'girl',
      ageLook: '7-year-old',
      skinTone: 'fair',
      eyeColor: 'hazel',
      faceShape: 'round-friendly',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'button',
      cheekStyle: 'rosy-round',
      hairStyle: 'chin-length bob',
      hairColor: 'auburn',
      topGarmentType: 'soft cardigan over flower tee',
      topGarmentColor: 'coral',
      topGarmentDetails: 'paw-print patch at the hem',
      bottomGarmentType: 'leggings',
      bottomGarmentColor: 'denim blue',
      shoeType: 'canvas shoes',
      shoeColor: 'white',
      bodyBuild: 'average build',
      heightFeel: 'small',
      heightCm: 121,
      weightKg: 23,
      accessories: ['scruffy cream puppy', 'blue leash'],
      paletteNotes: 'Coral, denim, cream - warm and playful',
    },
    palettePreview: { primary: '#FF7043', secondary: '#5C6BC0', accent: '#FFF3E0' },
  }),
  buildDefaultTemplate({
    _id: 'default_liam_stargazer',
    name: 'Liam - Star Map',
    description: 'A dreamy older boy with a telescope and notebook. Ideal for space books, observatory nights, and science adventures.',
    category: 'teen-boy',
    tags: ['universal', 'teen', 'boy', 'space', 'science', 'adventure'],
    traits: ['curious', 'patient', 'observant'],
    ageRange: '12-15',
    visualDNA: {
      gender: 'boy',
      ageLook: '13-year-old teenager',
      skinTone: 'light-beige',
      eyeColor: 'grey-blue',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'natural-full',
      noseStyle: 'straight-narrow',
      cheekStyle: 'light-defined',
      hairStyle: 'soft side-swept cut',
      hairColor: 'dark blond',
      topGarmentType: 'zip hoodie over constellations tee',
      topGarmentColor: 'midnight blue',
      topGarmentDetails: 'constellation patches on sleeve',
      bottomGarmentType: 'utility joggers',
      bottomGarmentColor: 'slate grey',
      shoeType: 'trail sneakers',
      shoeColor: 'white',
      bodyBuild: 'lean and lanky',
      heightFeel: 'tall',
      heightCm: 156,
      weightKg: 44,
      accessories: ['compact telescope', 'star chart notebook'],
      paletteNotes: 'Midnight blue, slate, white - thoughtful and cosmic',
    },
    modestyRules: { longSleeves: true },
    palettePreview: { primary: '#1A237E', secondary: '#546E7A', accent: '#CFD8DC' },
  }),
  buildDefaultTemplate({
    _id: 'default_priya_spark_lab',
    name: 'Priya - Spark Lab',
    description: 'A focused inventor with a tiny robot prototype and safety goggles. Great for maker stories, problem solving, and school projects.',
    category: 'teen-girl',
    tags: ['universal', 'teen', 'girl', 'inventor', 'science', 'robot'],
    traits: ['inventive', 'focused', 'optimistic'],
    ageRange: '12-16',
    visualDNA: {
      gender: 'girl',
      ageLook: '14-year-old teenager',
      skinTone: 'brown',
      eyeColor: 'dark-brown',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'small-straight',
      cheekStyle: 'soft-round',
      hairStyle: 'braided ponytail',
      hairColor: 'black',
      topGarmentType: 'rolled-sleeve utility jacket over tee',
      topGarmentColor: 'teal',
      topGarmentDetails: 'pocket stuffed with pencils',
      bottomGarmentType: 'straight jeans',
      bottomGarmentColor: 'dark indigo',
      shoeType: 'trainers',
      shoeColor: 'orange and white',
      bodyBuild: 'slim and steady',
      heightFeel: 'average height',
      heightCm: 158,
      weightKg: 47,
      glasses: 'clear safety goggles pushed up on head',
      accessories: ['tiny robot companion', 'screwdriver'],
      paletteNotes: 'Teal, indigo, orange - smart and energetic',
    },
    palettePreview: { primary: '#00897B', secondary: '#283593', accent: '#FB8C00' },
  }),
  buildDefaultTemplate({
    _id: 'default_kofi_goal_chaser',
    name: 'Kofi - Goal Chaser',
    description: 'A fast, laughing football kid with grass stains on his socks. Perfect for playground wins, teamwork, and sportsmanship.',
    category: 'boy',
    tags: ['universal', 'boy', 'sports', 'football', 'teamwork'],
    traits: ['energetic', 'friendly', 'competitive'],
    ageRange: '8-11',
    visualDNA: {
      gender: 'boy',
      ageLook: '9-year-old',
      skinTone: 'deep-brown',
      eyeColor: 'dark-brown',
      faceShape: 'round-friendly',
      eyebrowStyle: 'natural-full',
      noseStyle: 'rounded-soft',
      cheekStyle: 'dimpled',
      hairStyle: 'short coils',
      hairColor: 'black',
      topGarmentType: 'football jersey',
      topGarmentColor: 'royal blue',
      topGarmentDetails: 'white number 10 on chest',
      bottomGarmentType: 'sports shorts',
      bottomGarmentColor: 'white',
      shoeType: 'football boots',
      shoeColor: 'black and neon green',
      bodyBuild: 'athletic and lean',
      heightFeel: 'average height',
      heightCm: 130,
      weightKg: 28,
      accessories: ['football under foot'],
      paletteNotes: 'Royal blue, white, neon green - athletic and upbeat',
    },
    palettePreview: { primary: '#1565C0', secondary: '#FFFFFF', accent: '#7CB342' },
  }),
  buildDefaultTemplate({
    _id: 'default_oliver_starlift',
    name: 'Oliver - Starlift Cadet',
    description: 'A smiling space kid in a chunky training suit. Perfect for rockets, moon landings, and robot-sidekick adventures.',
    category: 'boy',
    tags: ['universal', 'boy', 'space', 'fantasy', 'robot', 'adventure'],
    traits: ['bold', 'curious', 'hopeful'],
    ageRange: '7-10',
    visualDNA: {
      gender: 'boy',
      ageLook: '8-year-old',
      skinTone: 'fair',
      eyeColor: 'grey',
      faceShape: 'round-friendly',
      eyebrowStyle: 'soft-straight',
      noseStyle: 'button',
      cheekStyle: 'soft-round',
      hairStyle: 'short tousled',
      hairColor: 'sand blond',
      topGarmentType: 'padded cadet jumpsuit',
      topGarmentColor: 'silver grey',
      topGarmentDetails: 'orange mission patches',
      bottomGarmentType: 'matching space trousers',
      bottomGarmentColor: 'silver grey',
      shoeType: 'moon boots',
      shoeColor: 'white and orange',
      bodyBuild: 'average build',
      heightFeel: 'average height',
      heightCm: 124,
      weightKg: 24,
      accessories: ['mini robot rover', 'bubble helmet tucked under arm'],
      paletteNotes: 'Silver, white, orange - bright sci-fi optimism',
    },
    modestyRules: { longSleeves: true },
    palettePreview: { primary: '#B0BEC5', secondary: '#ECEFF1', accent: '#FB8C00' },
  }),
  buildDefaultTemplate({
    _id: 'default_theo_hedgehog',
    name: 'Theo - Hedgehog Scout',
    description: 'A tiny hedgehog in a leaf cape who loves collecting buttons and moss. Perfect for woodland quests and cozy fantasy.',
    category: 'animal',
    tags: ['universal', 'animal', 'hedgehog', 'fantasy', 'woodland'],
    role: 'supporting',
    ageRange: 'n/a',
    traits: ['brave', 'tiny', 'loyal'],
    visualDNA: {
      gender: 'neutral',
      ageLook: 'small hedgehog',
      eyeColor: 'black',
      faceShape: 'pointed-cute',
      noseStyle: 'tiny-black-nose',
      hairColor: 'brown and cream spines',
      topGarmentType: 'leaf cape',
      topGarmentColor: 'forest green',
      topGarmentDetails: 'button clasp at neck',
      bodyBuild: 'tiny and round',
      heightFeel: 'very small',
      heightCm: 18,
      weightKg: 1,
      accessories: ['acorn satchel'],
      paletteNotes: 'Forest green, brown, cream - cozy woodland fantasy',
    },
    modestyRules: { looseClothing: false },
    palettePreview: { primary: '#2E7D32', secondary: '#8D6E63', accent: '#FFF8E1' },
  }),
  buildDefaultTemplate({
    _id: 'default_hazel_fox',
    name: 'Hazel - Lantern Fox',
    description: 'A clever amber fox carrying a tiny paper lantern. Great for nighttime wonder, magical forests, and gentle fantasy quests.',
    category: 'animal',
    tags: ['universal', 'animal', 'fox', 'fantasy', 'lantern'],
    role: 'supporting',
    ageRange: 'n/a',
    traits: ['clever', 'nimble', 'mysterious'],
    visualDNA: {
      gender: 'neutral',
      ageLook: 'young fox',
      eyeColor: 'gold',
      faceShape: 'sleek-friendly',
      noseStyle: 'small-black-nose',
      hairColor: 'amber-orange fur',
      topGarmentType: 'tiny scarf',
      topGarmentColor: 'teal',
      topGarmentDetails: 'paper lantern tied to tail ribbon',
      bodyBuild: 'small and nimble',
      heightFeel: 'small',
      heightCm: 32,
      weightKg: 5,
      accessories: ['mini lantern'],
      paletteNotes: 'Amber, teal, cream - magical twilight',
    },
    modestyRules: { looseClothing: false },
    palettePreview: { primary: '#F57C00', secondary: '#00897B', accent: '#FFF3E0' },
  }),
  buildDefaultTemplate({
    _id: 'default_finn_robot_pal',
    name: 'Finn - Robot Pal',
    description: 'A quick-witted kid with a backpack robot buddy. Perfect for futuristic neighborhoods, inventions, and comic adventures.',
    category: 'boy',
    tags: ['universal', 'boy', 'robot', 'science', 'adventure'],
    traits: ['quick-witted', 'inventive', 'loyal'],
    ageRange: '9-12',
    visualDNA: {
      gender: 'boy',
      ageLook: '10-year-old',
      skinTone: 'light-tan',
      eyeColor: 'brown',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'natural-full',
      noseStyle: 'rounded-soft',
      cheekStyle: 'soft-round',
      hairStyle: 'spiky crop',
      hairColor: 'dark-brown',
      topGarmentType: 'zip bomber jacket over tee',
      topGarmentColor: 'electric blue',
      topGarmentDetails: 'pixel bolt patch',
      bottomGarmentType: 'cargo joggers',
      bottomGarmentColor: 'graphite',
      shoeType: 'high-top trainers',
      shoeColor: 'white and aqua',
      bodyBuild: 'average build',
      heightFeel: 'average height',
      heightCm: 136,
      weightKg: 31,
      accessories: ['small backpack robot'],
      paletteNotes: 'Electric blue, graphite, aqua - playful sci-fi',
    },
    palettePreview: { primary: '#1E88E5', secondary: '#424242', accent: '#26C6DA' },
  }),
  buildDefaultTemplate({
    _id: 'default_ruby_map_runner',
    name: 'Ruby - Map Runner',
    description: 'A daring girl with a rolled treasure map and sea-worn satchel. Great for pirate-lite stories, clues, and island quests.',
    category: 'girl',
    tags: ['universal', 'girl', 'adventure', 'map', 'pirate'],
    traits: ['daring', 'quick-thinking', 'playful'],
    ageRange: '8-11',
    visualDNA: {
      gender: 'girl',
      ageLook: '9-year-old',
      skinTone: 'peach',
      eyeColor: 'sea-green',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'soft-arched',
      noseStyle: 'small-straight',
      cheekStyle: 'freckled',
      hairStyle: 'messy braid',
      hairColor: 'copper red',
      topGarmentType: 'striped sailor top',
      topGarmentColor: 'cream and navy',
      topGarmentDetails: 'tiny anchor patch',
      bottomGarmentType: 'adventure shorts over leggings',
      bottomGarmentColor: 'brick red',
      shoeType: 'lace-up boots',
      shoeColor: 'brown',
      bodyBuild: 'lean and quick',
      heightFeel: 'average height',
      heightCm: 128,
      weightKg: 26,
      accessories: ['rolled treasure map', 'weathered satchel'],
      paletteNotes: 'Cream, navy, brick red - nautical adventure',
    },
    palettePreview: { primary: '#3949AB', secondary: '#FFF8E1', accent: '#D84315' },
  }),
  buildDefaultTemplate({
    _id: 'default_leo_castle_squire',
    name: 'Leo - Castle Squire',
    description: 'A tiny toddler in a cardboard helmet with endless courage. Perfect for pretend play, dragons, and castle games.',
    category: 'toddler',
    tags: ['universal', 'toddler', 'boy', 'fantasy', 'castle'],
    traits: ['brave', 'giggly', 'imaginative'],
    ageRange: '2-4',
    visualDNA: {
      gender: 'boy',
      ageLook: '3-year-old toddler',
      skinTone: 'peach',
      eyeColor: 'brown',
      faceShape: 'round-youthful',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'button',
      cheekStyle: 'chubby-rosy',
      hairStyle: 'short fluffy',
      hairColor: 'brown',
      topGarmentType: 'soft tunic with cardboard armor',
      topGarmentColor: 'sky blue',
      topGarmentDetails: 'felt star on chest',
      bottomGarmentType: 'leggings',
      bottomGarmentColor: 'oatmeal',
      shoeType: 'soft boots',
      shoeColor: 'brown',
      bodyBuild: 'chubby and soft',
      heightFeel: 'very small',
      heightCm: 90,
      weightKg: 14,
      accessories: ['cardboard helmet', 'soft toy dragon'],
      paletteNotes: 'Sky blue, oatmeal, brown - cozy pretend play',
    },
    modestyRules: { longSleeves: true, looseClothing: false },
    palettePreview: { primary: '#64B5F6', secondary: '#D7CCC8', accent: '#8D6E63' },
  }),
  buildDefaultTemplate({
    _id: 'default_nora_grandma_baker',
    name: 'Grandma Nora - Apple Oven',
    description: 'A flour-dusted grandmother with a hug-ready apron and a tray of pies. Lovely for kitchen stories, family traditions, and kindness.',
    category: 'elder-female',
    tags: ['universal', 'elder', 'female', 'grandmother', 'baker', 'family'],
    role: 'supporting',
    traits: ['kind', 'patient', 'funny'],
    ageRange: '62-74',
    visualDNA: {
      gender: 'female',
      ageLook: 'elderly woman 68',
      skinTone: 'fair',
      eyeColor: 'blue-grey',
      faceShape: 'round-friendly',
      eyebrowStyle: 'soft-thin',
      noseStyle: 'rounded-soft',
      cheekStyle: 'soft-round',
      hairStyle: 'short curled bob',
      hairColor: 'silver',
      topGarmentType: 'long-sleeve blouse with apron',
      topGarmentColor: 'dusty blue',
      topGarmentDetails: 'apple motif apron pocket',
      bottomGarmentType: 'long skirt',
      bottomGarmentColor: 'warm grey',
      shoeType: 'house shoes',
      shoeColor: 'brown',
      bodyBuild: 'soft and rounded',
      heightFeel: 'average height',
      heightCm: 158,
      weightKg: 67,
      glasses: 'half-moon baking glasses',
      accessories: ['tray of mini pies'],
      paletteNotes: 'Dusty blue, warm grey, apple red - homey and welcoming',
    },
    modestyRules: { longSleeves: true },
    palettePreview: { primary: '#78909C', secondary: '#B0BEC5', accent: '#D84315' },
  }),
  buildDefaultTemplate({
    _id: 'default_ellis_tinkerer',
    name: 'Grandad Ellis - Pocket Clock',
    description: 'A tinkering grandfather with a vest full of tiny tools and stories. Great for workshops, memory books, and gentle inventions.',
    category: 'elder-male',
    tags: ['universal', 'elder', 'male', 'grandfather', 'inventor', 'workshop'],
    role: 'supporting',
    traits: ['wise', 'inventive', 'gentle'],
    ageRange: '64-76',
    visualDNA: {
      gender: 'male',
      ageLook: 'elderly man 70',
      skinTone: 'peach',
      eyeColor: 'hazel',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'bushy-straight',
      noseStyle: 'straight-narrow',
      cheekStyle: 'lined-kind',
      hairStyle: 'short silver side-part',
      hairColor: 'silver',
      topGarmentType: 'checked shirt with knit vest',
      topGarmentColor: 'forest green',
      topGarmentDetails: 'tiny watch chain across vest',
      bottomGarmentType: 'corduroy trousers',
      bottomGarmentColor: 'brown',
      shoeType: 'work shoes',
      shoeColor: 'tan',
      bodyBuild: 'wiry and steady',
      heightFeel: 'average height',
      heightCm: 170,
      weightKg: 71,
      facialHair: 'small silver moustache',
      glasses: 'round workshop glasses',
      accessories: ['pocket watch', 'mini toolkit'],
      paletteNotes: 'Forest green, brown, silver - warm workshop comfort',
    },
    modestyRules: { longSleeves: true },
    palettePreview: { primary: '#2E7D32', secondary: '#6D4C41', accent: '#B0BEC5' },
  }),
  buildDefaultTemplate({
    _id: 'default_sofia_booklane',
    name: 'Sofia - Book Lane',
    description: 'A calm teen who runs the class book swap and always has a recommendation ready. Great for school, friendship, and library stories.',
    category: 'teen-girl',
    tags: ['universal', 'teen', 'girl', 'books', 'school', 'friendship'],
    traits: ['calm', 'clever', 'encouraging'],
    ageRange: '13-16',
    visualDNA: {
      gender: 'girl',
      ageLook: '15-year-old teenager',
      skinTone: 'olive',
      eyeColor: 'green-brown',
      faceShape: 'heart-soft',
      eyebrowStyle: 'soft-arched',
      noseStyle: 'straight-narrow',
      cheekStyle: 'light-defined',
      hairStyle: 'wavy shoulder-length',
      hairColor: 'dark chestnut',
      topGarmentType: 'light sweater over collared shirt',
      topGarmentColor: 'berry red',
      topGarmentDetails: 'book-shaped enamel pin',
      bottomGarmentType: 'wide-leg trousers',
      bottomGarmentColor: 'charcoal',
      shoeType: 'ankle boots',
      shoeColor: 'tan',
      bodyBuild: 'average build',
      heightFeel: 'average height',
      heightCm: 162,
      weightKg: 51,
      glasses: 'round reading glasses',
      accessories: ['stack of library books'],
      paletteNotes: 'Berry, charcoal, tan - cozy and dependable',
    },
    modestyRules: { longSleeves: true },
    palettePreview: { primary: '#C62828', secondary: '#37474F', accent: '#A1887F' },
  }),
  buildDefaultTemplate({
    _id: 'default_clara_cloud_post',
    name: 'Clara - Cloud Post',
    description: 'A friendly adult balloon-post pilot who delivers letters between villages. Great for whimsical travel and community tales.',
    category: 'adult-female',
    tags: ['universal', 'adult', 'female', 'adventure', 'whimsical'],
    role: 'supporting',
    traits: ['friendly', 'reliable', 'brisk'],
    ageRange: '26-36',
    visualDNA: {
      gender: 'female',
      ageLook: 'adult woman 31',
      skinTone: 'light-olive',
      eyeColor: 'brown',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'soft-arched',
      noseStyle: 'straight-narrow',
      cheekStyle: 'light-defined',
      hairStyle: 'curly bun',
      hairColor: 'dark-brown',
      topGarmentType: 'pilot jacket over knit top',
      topGarmentColor: 'cranberry',
      topGarmentDetails: 'airmail patch on sleeve',
      bottomGarmentType: 'travel trousers',
      bottomGarmentColor: 'camel',
      shoeType: 'lace boots',
      shoeColor: 'brown',
      bodyBuild: 'average build',
      heightFeel: 'average height',
      heightCm: 167,
      weightKg: 58,
      accessories: ['mail satchel', 'aviator cap'],
      paletteNotes: 'Cranberry, camel, brown - warm whimsical travel',
    },
    modestyRules: { longSleeves: true },
    palettePreview: { primary: '#AD1457', secondary: '#D7B899', accent: '#6D4C41' },
  }),
];

// ─── Built-in default templates ───────────────────────────────────────────────
// These are always available to every user regardless of DB state.
const DEFAULT_TEMPLATES  = [
  // ─── GIRLS ────────────────────────────────────────────────────────────────
  {
    _id: 'default_hijabi_girl_autumn',
    name: 'Layla – Autumn Leaves',
    description: 'A thoughtful girl with a rust-orange hijab who loves reading and autumn walks. Perfect for stories about reflection and gratitude.',
    category: 'girl',
    thumbnailUrl: '',
    tags: ['hijabi', 'autumn', 'girl', 'thoughtful', 'reader'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '7-10',
    traits: ['thoughtful', 'gentle', 'imaginative'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'girl',
      ageLook: '8-year-old',
      skinTone: 'warm-olive',
      eyeColor: 'dark-brown',
      faceShape: 'oval-gentle',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'button',
      cheekStyle: 'soft-round',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'rust-orange-solid',
      hijabColor: 'rust-orange',
      topGarmentType: 'long-sleeve cardigan over tunic',
      topGarmentColor: 'cream',
      topGarmentDetails: 'small leaf-shaped buttons',
      bottomGarmentType: 'wide-leg trousers',
      bottomGarmentColor: 'warm-brown',
      shoeType: 'ankle boots',
      shoeColor: 'dark-brown',
      bodyBuild: 'average build',
      heightFeel: 'average height',
      heightCm: 122,
      weightKg: 24,
      facialHair: '',
      glasses: 'small round tortoiseshell glasses',
      accessories: ['small book under arm'],
      paletteNotes: 'Rust orange, warm brown, cream — autumn warmth',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#BF5700', secondary: '#C4A882', accent: '#FFF8F0' },
  },
  {
    _id: 'default_hijabi_girl_mint',
    name: 'Noor – Mint & Stars',
    description: 'A bright-eyed girl in a mint-green hijab who dreams of becoming a scientist. Great for STEM and curiosity-driven stories.',
    category: 'girl',
    thumbnailUrl: '',
    tags: ['hijabi', 'mint', 'girl', 'science', 'curious'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '8-11',
    traits: ['curious', 'determined', 'smart'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'girl',
      ageLook: '9-year-old',
      skinTone: 'light-beige',
      eyeColor: 'dark-brown',
      faceShape: 'round-friendly',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'button',
      cheekStyle: 'chubby-rosy',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'mint-green-solid',
      hijabColor: 'mint-green',
      topGarmentType: 'long-sleeve lab coat over modest top',
      topGarmentColor: 'white',
      topGarmentDetails: 'star-patch on left sleeve',
      bottomGarmentType: 'wide-leg trousers',
      bottomGarmentColor: 'navy',
      shoeType: 'sneakers',
      shoeColor: 'mint-green',
      bodyBuild: 'average build',
      heightFeel: 'small',
      heightCm: 128,
      weightKg: 26,
      facialHair: '',
      glasses: '',
      accessories: ['magnifying glass', 'star-patterned notebook'],
      paletteNotes: 'Mint green, navy, white — fresh and smart',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#4DB6AC', secondary: '#1A237E', accent: '#FFFFFF' },
  },
  {
    _id: 'default_sporty_girl',
    name: 'Hana – Green Fields',
    description: 'An energetic girl who loves football and the outdoors. Perfect for stories about teamwork, fair play, and confidence.',
    category: 'girl',
    thumbnailUrl: '',
    tags: ['girl', 'sporty', 'green', 'active', 'hijabi'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '9-12',
    traits: ['energetic', 'teamwork', 'confident'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'girl',
      ageLook: '10-year-old',
      skinTone: 'tan',
      eyeColor: 'dark-brown',
      faceShape: 'square-determined',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'rounded-soft',
      cheekStyle: 'flat-smooth',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'sports-hijab-green',
      hijabColor: 'grass-green',
      topGarmentType: 'long-sleeve sports jersey',
      topGarmentColor: 'grass-green',
      topGarmentDetails: 'number 7 on back',
      bottomGarmentType: 'loose sport trousers',
      bottomGarmentColor: 'white',
      shoeType: 'football boots',
      shoeColor: 'black and white',
      bodyBuild: 'athletic and lean',
      heightFeel: 'average height',
      heightCm: 138,
      weightKg: 32,
      facialHair: '',
      glasses: '',
      accessories: ['football under arm'],
      paletteNotes: 'Grass green, white, black — active and vibrant',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: false, notes: 'sports context' },
    palettePreview: { primary: '#388E3C', secondary: '#FFFFFF', accent: '#212121' },
  },

  // ─── BOYS ─────────────────────────────────────────────────────────────────
  {
    _id: 'default_kind_boy_red',
    name: 'Bilal – Red Cap',
    description: 'A warm-hearted boy who loves helping neighbours and feeding animals. Perfect for stories about generosity and community.',
    category: 'boy',
    thumbnailUrl: '',
    tags: ['boy', 'kind', 'red', 'community', 'helpful'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '6-9',
    traits: ['kind', 'generous', 'loyal'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'boy',
      ageLook: '7-year-old',
      skinTone: 'brown',
      eyeColor: 'dark-brown',
      faceShape: 'round-friendly',
      eyebrowStyle: 'natural-full',
      noseStyle: 'rounded-soft',
      cheekStyle: 'dimpled',
      hairStyle: 'short-afro',
      hairColor: 'black',
      hairVisibility: 'hidden',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'striped polo shirt',
      topGarmentColor: 'red and white stripes',
      topGarmentDetails: '',
      bottomGarmentType: 'cargo shorts',
      bottomGarmentColor: 'khaki',
      shoeType: 'sneakers',
      shoeColor: 'white',
      bodyBuild: 'average build',
      heightFeel: 'small',
      heightCm: 118,
      weightKg: 22,
      facialHair: '',
      glasses: '',
      accessories: ['red baseball cap worn backwards', 'small basket of food'],
      paletteNotes: 'Red, white, khaki — warm and cheerful',
    },
    modestyRules: { hijabAlways: false, longSleeves: false, looseClothing: true, notes: '' },
    palettePreview: { primary: '#D32F2F', secondary: '#EFEBE9', accent: '#8D6E63' },
  },
  {
    _id: 'default_boy_kufi_blue',
    name: 'Yusuf – Sky & Kufi',
    description: 'A gentle, devout boy wearing a white kufi. Ideal for stories about prayer, patience, and learning Islamic manners.',
    category: 'boy',
    thumbnailUrl: '',
    tags: ['boy', 'kufi', 'blue', 'faith', 'gentle'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '7-10',
    traits: ['patient', 'devout', 'gentle'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'boy',
      ageLook: '8-year-old',
      skinTone: 'golden',
      eyeColor: 'dark-brown',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'button',
      cheekStyle: 'soft-round',
      hairStyle: 'short-dark',
      hairColor: 'black',
      hairVisibility: 'hidden',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'long-sleeve thobe / kurta',
      topGarmentColor: 'sky-blue',
      topGarmentDetails: 'simple collar embroidery',
      bottomGarmentType: 'matching trousers',
      bottomGarmentColor: 'sky-blue',
      shoeType: 'leather sandals',
      shoeColor: 'beige',
      bodyBuild: 'average build',
      heightFeel: 'average height',
      heightCm: 124,
      weightKg: 25,
      facialHair: '',
      glasses: '',
      accessories: ['white kufi cap', 'small prayer rug rolled under arm'],
      paletteNotes: 'Sky blue, white, beige — calm and spiritual',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#29B6F6', secondary: '#FFFFFF', accent: '#C8A86C' },
  },
  {
    _id: 'default_teen_boy_green',
    name: 'Omar – Urban Green',
    description: 'A confident teenage boy who loves volunteering and street art. Perfect for stories about identity, purpose, and giving back.',
    category: 'teen-boy',
    thumbnailUrl: '',
    tags: ['teen', 'boy', 'green', 'urban', 'volunteer'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '14-17',
    traits: ['confident', 'creative', 'community-minded'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'boy',
      ageLook: '15-year-old teenager',
      skinTone: 'caramel',
      eyeColor: 'hazel',
      faceShape: 'square-determined',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'broad-flat',
      cheekStyle: 'high-defined',
      hairStyle: 'medium-fade-curly-top',
      hairColor: 'dark-brown',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'long-sleeve hoodie',
      topGarmentColor: 'olive-green',
      topGarmentDetails: 'small crescent moon badge on chest',
      bottomGarmentType: 'straight-leg jeans',
      bottomGarmentColor: 'dark indigo',
      shoeType: 'high-top sneakers',
      shoeColor: 'white',
      bodyBuild: 'athletic and lean',
      heightFeel: 'tall',
      heightCm: 172,
      weightKg: 62,
      facialHair: 'light stubble',
      glasses: '',
      accessories: ['spray paint can in bag', 'volunteer badge'],
      paletteNotes: 'Olive green, indigo, white — urban and grounded',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#558B2F', secondary: '#283593', accent: '#FFFFFF' },
  },

  // ─── TODDLERS ─────────────────────────────────────────────────────────────
  {
    _id: 'default_toddler_boy_red',
    name: 'Toddler Zaid – Apple Red',
    description: 'A chubby, cheerful toddler boy in apple-red overalls. Perfect for under-4 books about feelings and firsts.',
    category: 'toddler',
    thumbnailUrl: '',
    tags: ['toddler', 'boy', 'red', 'cute', 'young'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '2-4',
    traits: ['playful', 'giggly', 'curious'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'boy',
      ageLook: '2-year-old toddler',
      skinTone: 'tan',
      eyeColor: 'dark-brown',
      faceShape: 'round-youthful',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'button',
      cheekStyle: 'chubby-rosy',
      hairStyle: 'short-tuft',
      hairColor: 'black',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'bodysuit under overalls',
      topGarmentColor: 'white',
      topGarmentDetails: '',
      bottomGarmentType: 'dungaree overalls',
      bottomGarmentColor: 'apple-red',
      shoeType: 'soft velcro trainers',
      shoeColor: 'red',
      bodyBuild: 'chubby and soft',
      heightFeel: 'very small',
      heightCm: 85,
      weightKg: 13,
      facialHair: '',
      glasses: '',
      accessories: ['small rubber duck'],
      paletteNotes: 'Apple red, white — bright and babyish',
    },
    modestyRules: { hijabAlways: false, longSleeves: false, looseClothing: false, notes: '' },
    palettePreview: { primary: '#E53935', secondary: '#FFFFFF', accent: '#FFCA28' },
  },
  {
    _id: 'default_toddler_girl_lavender',
    name: 'Toddler Safiya – Lavender Cloud',
    description: 'A sleepy, sweet toddler girl wrapped in lavender. Great for bedtime and night-routine picture books.',
    category: 'toddler',
    thumbnailUrl: '',
    tags: ['toddler', 'girl', 'lavender', 'bedtime', 'soft'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '1-3',
    traits: ['gentle', 'dreamy', 'affectionate'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'girl',
      ageLook: '2-year-old toddler',
      skinTone: 'warm-olive',
      eyeColor: 'dark-brown',
      faceShape: 'round-youthful',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'button',
      cheekStyle: 'chubby-rosy',
      hairStyle: 'two-puffs',
      hairColor: 'black',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'puffy sleep onesie',
      topGarmentColor: 'lavender',
      topGarmentDetails: 'small cloud embroidery on chest',
      bottomGarmentType: 'built-in footies',
      bottomGarmentColor: 'lavender',
      shoeType: '',
      shoeColor: '',
      bodyBuild: 'chubby and soft',
      heightFeel: 'very small',
      heightCm: 80,
      weightKg: 12,
      facialHair: '',
      glasses: '',
      accessories: ['small stuffed lamb toy'],
      paletteNotes: 'Lavender, white — dreamy and soft',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: false, notes: '' },
    palettePreview: { primary: '#CE93D8', secondary: '#FFFFFF', accent: '#F3E5F5' },
  },

  // ─── ADULTS ───────────────────────────────────────────────────────────────
  {
    _id: 'default_young_mama',
    name: 'Mama Amira – Warm Rose',
    description: 'A kind and nurturing mother with a rose-pink hijab. Perfect as a loving, central parent figure in family stories.',
    category: 'adult-female',
    thumbnailUrl: '',
    tags: ['adult', 'female', 'hijabi', 'mother', 'family'],
    isDefault: true,
    role: 'supporting',
    ageRange: '28-36',
    traits: ['nurturing', 'patient', 'warm'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'female',
      ageLook: 'young adult woman 30',
      skinTone: 'light-beige',
      eyeColor: 'dark-brown',
      faceShape: 'oval-gentle',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'straight-narrow',
      cheekStyle: 'soft-round',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'rose-pink-wrapped',
      hijabColor: 'rose-pink',
      topGarmentType: 'long-sleeve modest blouse',
      topGarmentColor: 'white',
      topGarmentDetails: 'delicate floral print',
      bottomGarmentType: 'long modest skirt',
      bottomGarmentColor: 'mauve',
      shoeType: 'flat ballet shoes',
      shoeColor: 'nude',
      bodyBuild: 'average build',
      heightFeel: 'average height',
      heightCm: 160,
      weightKg: 60,
      facialHair: '',
      glasses: '',
      accessories: ['apron tied at waist', 'small basket'],
      paletteNotes: 'Rose pink, white, mauve — gentle and homey',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#E91E8C', secondary: '#CE93D8', accent: '#FFFFFF' },
  },
  {
    _id: 'default_young_baba',
    name: 'Baba Tariq – Navy & Wood',
    description: 'A strong and caring father with a warm smile. Great for family stories about guidance, protection, and love.',
    category: 'adult-male',
    thumbnailUrl: '',
    tags: ['adult', 'male', 'father', 'family', 'navy'],
    isDefault: true,
    role: 'supporting',
    ageRange: '30-40',
    traits: ['protective', 'wise', 'loving'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'male',
      ageLook: 'adult man 35',
      skinTone: 'golden',
      eyeColor: 'dark-brown',
      faceShape: 'square-determined',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'broad-flat',
      cheekStyle: 'high-defined',
      hairStyle: 'short-neat-fade',
      hairColor: 'black',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'long-sleeve button-up shirt',
      topGarmentColor: 'navy',
      topGarmentDetails: 'rolled sleeves',
      bottomGarmentType: 'chinos',
      bottomGarmentColor: 'tan',
      shoeType: 'leather shoes',
      shoeColor: 'brown',
      bodyBuild: 'broad-shouldered, fit',
      heightFeel: 'tall',
      heightCm: 178,
      weightKg: 80,
      facialHair: 'short trimmed beard',
      glasses: '',
      accessories: ['wristwatch'],
      paletteNotes: 'Navy, tan, brown — strong and warm',
    },
    modestyRules: { hijabAlways: false, longSleeves: false, looseClothing: true, notes: '' },
    palettePreview: { primary: '#1565C0', secondary: '#BCAAA4', accent: '#5D4037' },
  },
  {
    _id: 'default_teacher_lady',
    name: 'Ustadha Zainab – Sage Scholar',
    description: 'A warm and knowledgeable female teacher with a sage-green hijab. Ideal for school and Islamic learning stories.',
    category: 'adult-female',
    thumbnailUrl: '',
    tags: ['adult', 'female', 'hijabi', 'teacher', 'sage', 'school'],
    isDefault: true,
    role: 'supporting',
    ageRange: '30-45',
    traits: ['knowledgeable', 'patient', 'encouraging'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'female',
      ageLook: 'adult woman 38',
      skinTone: 'warm-olive',
      eyeColor: 'hazel',
      faceShape: 'oval-gentle',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'rounded-soft',
      cheekStyle: 'high-defined',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'sage-green-wrapped',
      hijabColor: 'sage-green',
      topGarmentType: 'long-sleeve modest blazer',
      topGarmentColor: 'sage-green',
      topGarmentDetails: '',
      bottomGarmentType: 'long modest skirt',
      bottomGarmentColor: 'cream',
      shoeType: 'low-heel pumps',
      shoeColor: 'nude',
      bodyBuild: 'average build',
      heightFeel: 'average height',
      heightCm: 163,
      weightKg: 62,
      facialHair: '',
      glasses: 'thin gold-frame rectangles',
      accessories: ['Quran or textbook in hand', 'marker pen'],
      paletteNotes: 'Sage green, cream, gold — scholarly and warm',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#7CB893', secondary: '#FFF8E1', accent: '#C9A86C' },
  },
  {
    _id: 'default_doctor_uncle',
    name: 'Dr. Khalid – White Coat',
    description: 'A reassuring Muslim doctor with a gentle manner. Perfect for stories about health, care, and trust.',
    category: 'adult-male',
    thumbnailUrl: '',
    tags: ['adult', 'male', 'doctor', 'health', 'professional'],
    isDefault: true,
    role: 'supporting',
    ageRange: '35-50',
    traits: ['calm', 'skilled', 'compassionate'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'male',
      ageLook: 'adult man 42',
      skinTone: 'caramel',
      eyeColor: 'dark-brown',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'straight-narrow',
      cheekStyle: 'high-defined',
      hairStyle: 'short-neat',
      hairColor: 'salt-and-pepper',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'white doctor coat over scrubs',
      topGarmentColor: 'white',
      topGarmentDetails: 'name badge',
      bottomGarmentType: 'scrub trousers',
      bottomGarmentColor: 'light-blue',
      shoeType: 'closed-toe medical shoes',
      shoeColor: 'white',
      bodyBuild: 'average build',
      heightFeel: 'tall',
      heightCm: 176,
      weightKg: 78,
      facialHair: 'short neatly trimmed beard',
      glasses: '',
      accessories: ['stethoscope around neck', 'clipboard'],
      paletteNotes: 'White, light blue — clean and professional',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#FFFFFF', secondary: '#B3E5FC', accent: '#01579B' },
  },

  // ─── ELDERS ───────────────────────────────────────────────────────────────
  {
    _id: 'default_elder_uncle',
    name: 'Uncle Hamid – Desert Gold',
    description: 'A cheerful and storytelling elder uncle with a golden kufi. Perfect for cultural and heritage stories.',
    category: 'elder-male',
    thumbnailUrl: '',
    tags: ['elder', 'male', 'storyteller', 'kufi', 'gold'],
    isDefault: true,
    role: 'supporting',
    ageRange: '55-65',
    traits: ['humorous', 'wise', 'storyteller'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'male',
      ageLook: 'middle-aged elder 60',
      skinTone: 'golden',
      eyeColor: 'brown',
      faceShape: 'round-friendly',
      eyebrowStyle: 'bushy-straight',
      noseStyle: 'broad-flat',
      cheekStyle: 'soft-round',
      hairStyle: 'short-white',
      hairColor: 'white',
      hairVisibility: 'hidden',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'long kurta / thobe',
      topGarmentColor: 'sandy gold',
      topGarmentDetails: 'geometric trim on collar',
      bottomGarmentType: 'matching wide trousers',
      bottomGarmentColor: 'sandy gold',
      shoeType: 'leather sandals',
      shoeColor: 'tan',
      bodyBuild: 'slightly rounded, stocky',
      heightFeel: 'average height',
      heightCm: 165,
      weightKg: 82,
      facialHair: 'full salt-and-pepper beard',
      glasses: '',
      accessories: ['gold embroidered kufi', 'walking cane'],
      paletteNotes: 'Sandy gold, tan, white — warm desert tones',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#F9A825', secondary: '#BCAAA4', accent: '#6D4C41' },
  },
  {
    _id: 'default_auntie_teal',
    name: 'Aunty Fatima – Teal Grace',
    description: 'A lively and crafty auntie with a teal hijab who loves cooking and sewing. Great for cultural and community stories.',
    category: 'elder-female',
    thumbnailUrl: '',
    tags: ['elder', 'female', 'hijabi', 'auntie', 'teal', 'craft'],
    isDefault: true,
    role: 'supporting',
    ageRange: '45-60',
    traits: ['lively', 'creative', 'generous'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'female',
      ageLook: 'middle-aged woman 50',
      skinTone: 'warm-olive',
      eyeColor: 'dark-brown',
      faceShape: 'round-friendly',
      eyebrowStyle: 'thin-straight',
      noseStyle: 'rounded-soft',
      cheekStyle: 'soft-round',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'teal-wrapped',
      hijabColor: 'teal',
      topGarmentType: 'long-sleeve modest blouse',
      topGarmentColor: 'teal',
      topGarmentDetails: 'floral embroidery on cuffs',
      bottomGarmentType: 'long flowy skirt',
      bottomGarmentColor: 'burnt-orange',
      shoeType: 'soft flat mules',
      shoeColor: 'tan',
      bodyBuild: 'slightly rounded',
      heightFeel: 'average height',
      heightCm: 157,
      weightKg: 70,
      facialHair: '',
      glasses: 'square reading glasses',
      accessories: ['wooden spoon', 'apron with floral print'],
      paletteNotes: 'Teal, burnt orange, tan — vibrant and homey',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#00897B', secondary: '#BF360C', accent: '#EFEBE9' },
  },

  // ─── ANIMALS / COMPANIONS ─────────────────────────────────────────────────
  {
    _id: 'default_white_cat',
    name: 'Luna – White Cat',
    description: 'A fluffy, curious white cat companion. Perfect for stories about loyalty, friendship, and home life.',
    category: 'animal',
    thumbnailUrl: '',
    tags: ['animal', 'cat', 'white', 'companion', 'fluffy'],
    isDefault: true,
    role: 'supporting',
    ageRange: 'n/a',
    traits: ['curious', 'affectionate', 'playful'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'neutral',
      ageLook: 'small adult cat',
      skinTone: '',
      eyeColor: 'bright-green',
      faceShape: 'round-friendly',
      eyebrowStyle: '',
      noseStyle: 'pink-button',
      cheekStyle: 'chubby-rosy',
      hairStyle: '',
      hairColor: 'pure-white',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: '',
      topGarmentColor: 'white fur',
      topGarmentDetails: 'fluffy tail with peach tip',
      bottomGarmentType: '',
      bottomGarmentColor: '',
      shoeType: '',
      shoeColor: '',
      bodyBuild: 'small and fluffy',
      heightFeel: 'very small',
      heightCm: 25,
      weightKg: 3,
      facialHair: '',
      glasses: '',
      accessories: [],
      paletteNotes: 'Pure white, peach nose — soft and clean',
    },
    modestyRules: { hijabAlways: false, longSleeves: false, looseClothing: false, notes: '' },
    palettePreview: { primary: '#FFFFFF', secondary: '#FFCCBC', accent: '#80CBC4' },
  },
  {
    _id: 'default_brown_horse',
    name: 'Rih – Brown Horse',
    description: 'A noble chestnut horse companion. Ideal for desert, history, and adventure stories with an Islamic setting.',
    category: 'animal',
    thumbnailUrl: '',
    tags: ['animal', 'horse', 'brown', 'noble', 'adventure'],
    isDefault: true,
    role: 'supporting',
    ageRange: 'n/a',
    traits: ['loyal', 'brave', 'strong'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'male',
      ageLook: 'adult horse',
      skinTone: '',
      eyeColor: 'dark-brown',
      faceShape: 'elongated-noble',
      eyebrowStyle: '',
      noseStyle: '',
      cheekStyle: '',
      hairStyle: 'long-flowing-mane',
      hairColor: 'chestnut-brown',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: '',
      topGarmentColor: 'chestnut-brown',
      topGarmentDetails: 'dark-brown mane and tail',
      bottomGarmentType: '',
      bottomGarmentColor: '',
      shoeType: 'hooves',
      shoeColor: 'dark-brown',
      bodyBuild: 'muscular and tall',
      heightFeel: 'very tall',
      heightCm: 155,
      weightKg: 250,
      facialHair: '',
      glasses: '',
      accessories: ['decorative saddle in red and gold'],
      paletteNotes: 'Chestnut brown, red, gold — desert noble',
    },
    modestyRules: { hijabAlways: false, longSleeves: false, looseClothing: false, notes: '' },
    palettePreview: { primary: '#795548', secondary: '#BF360C', accent: '#F9A825' },
  },
  {
    _id: 'default_green_parrot',
    name: 'Khadra – Green Parrot',
    description: 'A talkative bright-green parrot who loves repeating dhikr. Perfect for humorous and spiritual companion roles.',
    category: 'animal',
    thumbnailUrl: '',
    tags: ['animal', 'parrot', 'green', 'dhikr', 'funny'],
    isDefault: true,
    role: 'supporting',
    ageRange: 'n/a',
    traits: ['talkative', 'funny', 'spiritual'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'neutral',
      ageLook: 'adult parrot',
      skinTone: '',
      eyeColor: 'bright-yellow',
      faceShape: 'round-friendly',
      eyebrowStyle: '',
      noseStyle: 'hooked-beak',
      cheekStyle: '',
      hairStyle: '',
      hairColor: 'emerald-green',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: '',
      topGarmentColor: 'emerald-green',
      topGarmentDetails: 'red wing-feather tips, yellow collar ring',
      bottomGarmentType: '',
      bottomGarmentColor: '',
      shoeType: 'talons',
      shoeColor: 'grey',
      bodyBuild: 'small and sleek',
      heightFeel: 'very small',
      heightCm: 30,
      weightKg: 0,
      facialHair: '',
      glasses: '',
      accessories: [],
      paletteNotes: 'Emerald green, red tips, yellow ring',
    },
    modestyRules: { hijabAlways: false, longSleeves: false, looseClothing: false, notes: '' },
    palettePreview: { primary: '#2E7D32', secondary: '#D32F2F', accent: '#F9A825' },
  },

  // ─── SPECIAL / DIVERSE ROLES ──────────────────────────────────────────────
  {
    _id: 'default_wheelchair_girl',
    name: 'Iman – Purple Wheels',
    description: 'A bright and determined girl in a wheelchair with a purple hijab. Perfect for stories about courage, inclusion, and capability.',
    category: 'girl',
    thumbnailUrl: '',
    tags: ['hijabi', 'girl', 'wheelchair', 'inclusive', 'purple', 'determined'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '8-12',
    traits: ['determined', 'resilient', 'cheerful'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'girl',
      ageLook: '10-year-old',
      skinTone: 'caramel',
      eyeColor: 'dark-brown',
      faceShape: 'round-friendly',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'button',
      cheekStyle: 'chubby-rosy',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'purple-solid',
      hijabColor: 'purple',
      topGarmentType: 'long-sleeve modest top',
      topGarmentColor: 'lavender',
      topGarmentDetails: 'heart patch on sleeve',
      bottomGarmentType: 'wide-leg trousers',
      bottomGarmentColor: 'dark-purple',
      shoeType: 'soft-toe trainers',
      shoeColor: 'white',
      bodyBuild: 'average build',
      heightFeel: 'small',
      heightCm: 130,
      weightKg: 27,
      facialHair: '',
      glasses: '',
      accessories: ['modern purple wheelchair', 'small trophy on lap'],
      paletteNotes: 'Purple, lavender, white — bold and hopeful',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#7B1FA2', secondary: '#CE93D8', accent: '#FFFFFF' },
  },
  {
    _id: 'default_convert_sister',
    name: 'Sister Sara – New Light',
    description: 'A young convert wearing a simple white hijab with a warm, open expression. Great for stories about faith journeys and belonging.',
    category: 'teen-girl',
    thumbnailUrl: '',
    tags: ['hijabi', 'teen', 'girl', 'convert', 'white', 'faith'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '17-22',
    traits: ['hopeful', 'open-hearted', 'sincere'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'girl',
      ageLook: '19-year-old young adult',
      skinTone: 'fair',
      eyeColor: 'blue-grey',
      faceShape: 'oval-gentle',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'straight-narrow',
      cheekStyle: 'high-defined',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'simple-white-wrapped',
      hijabColor: 'white',
      topGarmentType: 'modest long-sleeve blouse',
      topGarmentColor: 'pale-blue',
      topGarmentDetails: '',
      bottomGarmentType: 'long flowy skirt',
      bottomGarmentColor: 'light-grey',
      shoeType: 'flat loafers',
      shoeColor: 'white',
      bodyBuild: 'slim and lean',
      heightFeel: 'average height',
      heightCm: 165,
      weightKg: 55,
      facialHair: '',
      glasses: '',
      accessories: ['small Quran in hand'],
      paletteNotes: 'White, pale blue, light grey — calm and fresh',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#FFFFFF', secondary: '#B0BEC5', accent: '#90CAF9' },
  },
  {
    _id: 'default_masjid_custodian',
    name: 'Uncle Sami – Masjid Keeper',
    description: 'A humble and devoted masjid custodian with a kind smile. Perfect for stories about service, prayer, and community.',
    category: 'adult-male',
    thumbnailUrl: '',
    tags: ['adult', 'male', 'masjid', 'custodian', 'humble', 'service'],
    isDefault: true,
    role: 'supporting',
    ageRange: '50-60',
    traits: ['humble', 'devoted', 'helpful'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'male',
      ageLook: 'older adult man 55',
      skinTone: 'brown',
      eyeColor: 'dark-brown',
      faceShape: 'round-friendly',
      eyebrowStyle: 'bushy-straight',
      noseStyle: 'broad-flat',
      cheekStyle: 'soft-round',
      hairStyle: 'short-grey',
      hairColor: 'salt-and-pepper',
      hairVisibility: 'hidden',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'long thobe',
      topGarmentColor: 'pale-grey',
      topGarmentDetails: '',
      bottomGarmentType: 'matching trousers',
      bottomGarmentColor: 'pale-grey',
      shoeType: 'slip-on sandals',
      shoeColor: 'dark-brown',
      bodyBuild: 'stocky, average',
      heightFeel: 'average height',
      heightCm: 167,
      weightKg: 80,
      facialHair: 'full grey beard',
      glasses: '',
      accessories: ['white kufi', 'broom or mop', 'prayer beads'],
      paletteNotes: 'Pale grey, white, brown — humble and serene',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#BDBDBD', secondary: '#FFFFFF', accent: '#795548' },
  },
  {
    _id: 'default_baby_newborn',
    name: 'Baby Yaqeen – Pink Swaddle',
    description: 'A tiny sleeping newborn swaddled in soft pink. Ideal for birth stories, new sibling books, and welcoming a baby.',
    category: 'toddler',
    thumbnailUrl: '',
    tags: ['baby', 'newborn', 'pink', 'sleeping', 'tiny'],
    isDefault: true,
    role: 'supporting',
    ageRange: '0-1',
    traits: ['peaceful', 'tiny', 'new'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'girl',
      ageLook: 'newborn baby',
      skinTone: 'light-beige',
      eyeColor: 'dark-brown',
      faceShape: 'round-youthful',
      eyebrowStyle: 'soft-rounded',
      noseStyle: 'tiny-button',
      cheekStyle: 'chubby-rosy',
      hairStyle: 'wisp-of-dark-hair',
      hairColor: 'dark-brown',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'swaddle blanket',
      topGarmentColor: 'blush-pink',
      topGarmentDetails: 'crescent moon and star pattern',
      bottomGarmentType: '',
      bottomGarmentColor: '',
      shoeType: '',
      shoeColor: '',
      bodyBuild: 'tiny and soft',
      heightFeel: 'very small',
      heightCm: 50,
      weightKg: 3,
      facialHair: '',
      glasses: '',
      accessories: [],
      paletteNotes: 'Blush pink, white, soft cream',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: false, notes: '' },
    palettePreview: { primary: '#F8BBD0', secondary: '#FFFFFF', accent: '#CE93D8' },
  },
  {
    _id: 'default_grandpa_farmer',
    name: 'Grandpa Hasan – Garden Sage',
    description: 'A gentle and earthy grandfather who tends his garden. Ideal for nature, gratitude, and seasons stories.',
    category: 'elder-male',
    thumbnailUrl: '',
    tags: ['elder', 'male', 'farmer', 'garden', 'nature', 'grandfather'],
    isDefault: true,
    role: 'supporting',
    ageRange: '65-75',
    traits: ['patient', 'earthy', 'peaceful'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'male',
      ageLook: 'elderly man 68',
      skinTone: 'tan',
      eyeColor: 'brown',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'bushy-straight',
      noseStyle: 'rounded-soft',
      cheekStyle: 'soft-round',
      hairStyle: 'short-white',
      hairColor: 'white',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'long-sleeve simple work shirt',
      topGarmentColor: 'denim-blue',
      topGarmentDetails: 'patch pockets',
      bottomGarmentType: 'gardening overalls',
      bottomGarmentColor: 'olive-green',
      shoeType: 'rubber boots',
      shoeColor: 'dark-green',
      bodyBuild: 'wiry and lean',
      heightFeel: 'average height',
      heightCm: 166,
      weightKg: 68,
      facialHair: 'short white stubble',
      glasses: 'simple reading glasses tucked in pocket',
      accessories: ['garden trowel', 'wide straw hat'],
      paletteNotes: 'Denim blue, olive green, tan — earthy and natural',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#1976D2', secondary: '#558B2F', accent: '#F9A825' },
  },
  {
    _id: 'default_young_imam',
    name: 'Imam Ibrahim – White & Gold',
    description: 'A young, approachable imam with a neatly trimmed beard and a warm expression. Perfect for masjid and community guidance stories.',
    category: 'adult-male',
    thumbnailUrl: '',
    tags: ['adult', 'male', 'imam', 'gold', 'white', 'faith', 'leader'],
    isDefault: true,
    role: 'supporting',
    ageRange: '28-40',
    traits: ['approachable', 'knowledgeable', 'calm'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'male',
      ageLook: 'young adult man 32',
      skinTone: 'warm-olive',
      eyeColor: 'dark-brown',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'straight-narrow',
      cheekStyle: 'high-defined',
      hairStyle: 'short-neat',
      hairColor: 'black',
      hairVisibility: 'hidden',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'long thobe / jubbah',
      topGarmentColor: 'white',
      topGarmentDetails: 'gold embroidery on collar and cuffs',
      bottomGarmentType: 'matching trousers',
      bottomGarmentColor: 'white',
      shoeType: 'leather mules',
      shoeColor: 'tan',
      bodyBuild: 'average build',
      heightFeel: 'tall',
      heightCm: 175,
      weightKg: 73,
      facialHair: 'short neat beard',
      glasses: '',
      accessories: ['white kufi with gold trim', 'Quran in right hand'],
      paletteNotes: 'White, gold, tan — dignified and welcoming',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#FFFFFF', secondary: '#C9A86C', accent: '#8D6E63' },
  },
  {
    _id: 'default_teen_hijabi_artist',
    name: 'Mariam – Art & Indigo',
    description: 'A creative teenage girl with an indigo hijab who expresses herself through calligraphy and painting.',
    category: 'teen-girl',
    thumbnailUrl: '',
    tags: ['teen', 'hijabi', 'girl', 'art', 'indigo', 'creative'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '13-16',
    traits: ['creative', 'introspective', 'determined'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'girl',
      ageLook: '15-year-old teenager',
      skinTone: 'warm-olive',
      eyeColor: 'dark-brown',
      faceShape: 'oval-gentle',
      eyebrowStyle: 'thick-arched',
      noseStyle: 'rounded-soft',
      cheekStyle: 'high-defined',
      hairStyle: '',
      hairColor: '',
      hairVisibility: 'hidden',
      hijabStyle: 'indigo-wrapped',
      hijabColor: 'indigo',
      topGarmentType: 'long-sleeve modest blouse',
      topGarmentColor: 'off-white',
      topGarmentDetails: 'small ink-splash stain — intentional',
      bottomGarmentType: 'wide-leg trousers',
      bottomGarmentColor: 'charcoal',
      shoeType: 'canvas sneakers',
      shoeColor: 'off-white',
      bodyBuild: 'slim and lean',
      heightFeel: 'average height',
      heightCm: 160,
      weightKg: 50,
      facialHair: '',
      glasses: '',
      accessories: ['calligraphy brush', 'paint-stained tote bag'],
      paletteNotes: 'Indigo, off-white, charcoal — artistic and bold',
    },
    modestyRules: { hijabAlways: true, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#283593', secondary: '#F5F5F0', accent: '#37474F' },
  },
  {
    _id: 'default_refugee_boy',
    name: 'Tariq – Hopeful Journey',
    description: 'A resilient boy carrying a small suitcase and a determined look. Perfect for stories about displacement, hope, and new beginnings.',
    category: 'boy',
    thumbnailUrl: '',
    tags: ['boy', 'journey', 'hope', 'resilient', 'earth-tones'],
    isDefault: true,
    role: 'protagonist',
    ageRange: '9-12',
    traits: ['resilient', 'hopeful', 'brave'],
    visualDNA: {
      style: 'pixar-3d',
      gender: 'boy',
      ageLook: '10-year-old',
      skinTone: 'caramel',
      eyeColor: 'dark-brown',
      faceShape: 'oval-balanced',
      eyebrowStyle: 'natural-full',
      noseStyle: 'rounded-soft',
      cheekStyle: 'dimpled',
      hairStyle: 'short-wavy-dark',
      hairColor: 'dark-brown',
      hairVisibility: 'visible',
      hijabStyle: '',
      hijabColor: '',
      topGarmentType: 'long-sleeve jersey',
      topGarmentColor: 'olive-green',
      topGarmentDetails: '',
      bottomGarmentType: 'straight jeans',
      bottomGarmentColor: 'dark-blue',
      shoeType: 'worn sneakers',
      shoeColor: 'grey',
      bodyBuild: 'slim and lean',
      heightFeel: 'average height',
      heightCm: 135,
      weightKg: 30,
      facialHair: '',
      glasses: '',
      accessories: ['small worn suitcase', 'toy key on a string around neck'],
      paletteNotes: 'Olive green, dark blue, grey — muted and grounded',
    },
    modestyRules: { hijabAlways: false, longSleeves: true, looseClothing: true, notes: '' },
    palettePreview: { primary: '#558B2F', secondary: '#283593', accent: '#90A4AE' },
  },
  ...UNIVERSAL_DEFAULT_TEMPLATES,
];

// ─── Helper: null-safe normaliser for lean() DB results ──────────────────────
function sanitizeTemplate(t) {
  const v = t.visualDNA || {};
  return {
    ...t,
    description: t.description ?? '',
    ageRange: t.ageRange ?? '',
    role: t.role ?? 'supporting',
    thumbnailUrl: t.thumbnailUrl ?? '',
    tags: Array.isArray(t.tags) ? t.tags : [],
    traits: Array.isArray(t.traits) ? t.traits : [],
    visualDNA: {
      style: v.style ?? '',
      gender: v.gender ?? '',
      ageLook: v.ageLook ?? '',
      skinTone: v.skinTone ?? '',
      eyeColor: v.eyeColor ?? '',
      faceShape: v.faceShape ?? '',
      eyebrowStyle: v.eyebrowStyle ?? '',
      noseStyle: v.noseStyle ?? '',
      cheekStyle: v.cheekStyle ?? '',
      hairStyle: v.hairStyle ?? '',
      hairColor: v.hairColor ?? '',
      hairVisibility: v.hairVisibility ?? 'visible',
      hijabStyle: v.hijabStyle ?? '',
      hijabColor: v.hijabColor ?? '',
      topGarmentType: v.topGarmentType ?? '',
      topGarmentColor: v.topGarmentColor ?? '',
      topGarmentDetails: v.topGarmentDetails ?? '',
      bottomGarmentType: v.bottomGarmentType ?? '',
      bottomGarmentColor: v.bottomGarmentColor ?? '',
      shoeType: v.shoeType ?? '',
      shoeColor: v.shoeColor ?? '',
      bodyBuild: v.bodyBuild ?? '',
      heightFeel: v.heightFeel ?? '',
      heightCm: v.heightCm ?? 0,
      weightKg: v.weightKg ?? 0,
      facialHair: v.facialHair ?? '',
      glasses: v.glasses ?? '',
      accessories: Array.isArray(v.accessories) ? v.accessories : [],
      paletteNotes: v.paletteNotes ?? '',
    },
    modestyRules: {
      hijabAlways: t.modestyRules?.hijabAlways ?? false,
      longSleeves: t.modestyRules?.longSleeves ?? false,
      looseClothing: t.modestyRules?.looseClothing ?? true,
      notes: t.modestyRules?.notes ?? '',
    },
    palettePreview: {
      primary: t.palettePreview?.primary ?? '',
      secondary: t.palettePreview?.secondary ?? '',
      accent: t.palettePreview?.accent ?? '',
    },
  };
}

// ─── Helper: merge default template thumbnail overrides from DB ───────────────
async function mergeDefaultThumbnails(defaults) {
  const refs = defaults.map((t) => t._id);
  const overrides = await CharacterTemplate.find({ defaultTemplateRef: { $in: refs } }).lean();
  const overrideMap = {};
  for (const o of overrides) overrideMap[o.defaultTemplateRef] = o.thumbnailUrl;
  return defaults.map((t) => overrideMap[t._id] ? { ...t, thumbnailUrl: overrideMap[t._id] } : t);
}

// ─── GET /api/character-templates ────────────────────────────────────────────
router.get('/', async (req, res, next) => {
  try {
    const query = req.user
      ? { defaultTemplateRef: '', $or: [{ createdBy: req.user._id }, { isPublic: true }] }
      : { defaultTemplateRef: '', isPublic: true };

    const [rawUserTemplates, defaultsWithThumbnails] = await Promise.all([
      CharacterTemplate.find(query).sort({ createdAt: -1 }).lean(),
      mergeDefaultThumbnails(DEFAULT_TEMPLATES),
    ]);

    const userTemplates = rawUserTemplates.map(sanitizeTemplate);
    res.json([...defaultsWithThumbnails, ...userTemplates]);
  } catch (e) {
    next(e);
  }
});

// ─── GET /api/character-templates/defaults ───────────────────────────────────
router.get('/defaults', async (req, res, next) => {
  try {
    res.json(await mergeDefaultThumbnails(DEFAULT_TEMPLATES));
  } catch (e) {
    next(e);
  }
});

// ─── PATCH /api/character-templates/:id/thumbnail ────────────────────────────
router.patch('/:id/thumbnail', async (req, res, next) => {
  try {
    const { thumbnailUrl } = req.body;
    if (!thumbnailUrl) return res.status(400).json({ error: { code: 'VALIDATION', message: 'thumbnailUrl is required' } });

    const isDefault = DEFAULT_TEMPLATES.some((t) => t._id === req.params.id);

    if (isDefault) {
      const defTpl = DEFAULT_TEMPLATES.find((t) => t._id === req.params.id);
      // Upsert an override document for this default template
      await CharacterTemplate.findOneAndUpdate(
        { defaultTemplateRef: req.params.id },
        { $set: { thumbnailUrl }, $setOnInsert: { defaultTemplateRef: req.params.id, name: defTpl.name, category: defTpl.category, isDefault: false } },
        { upsert: true, new: true, runValidators: true }
      );
    } else {
      const tpl = await CharacterTemplate.findOne({ _id: req.params.id });
      if (!tpl) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Template not found' } });
      tpl.thumbnailUrl = thumbnailUrl;
      await tpl.save();
    }

    res.json({ message: 'Thumbnail updated', thumbnailUrl });
  } catch (e) {
    next(e);
  }
});

// ─── GET /api/character-templates/:id ────────────────────────────────────────
router.get('/:id', async (req, res, next) => {
  try {
    // Check built-in defaults first (with thumbnail override)
    const def = DEFAULT_TEMPLATES.find((t) => t._id === req.params.id);
    if (def) {
      const override = await CharacterTemplate.findOne({ defaultTemplateRef: req.params.id }).lean();
      return res.json(override?.thumbnailUrl ? { ...def, thumbnailUrl: override.thumbnailUrl } : def);
    }

    const tpl = await CharacterTemplate.findById(req.params.id).lean();
    if (!tpl) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Template not found' } });

    res.json(sanitizeTemplate(tpl));
  } catch (e) {
    next(e);
  }
});

// ─── POST /api/character-templates — save an existing character as template ──
router.post('/', async (req, res, next) => {
  try {
    const {
      name,
      description = '',
      category,
      characterId,
      tags = [],
      isPublic = false,
    } = req.body;

    if (!name) return res.status(400).json({ error: { code: 'VALIDATION', message: 'name is required' } });
    if (!category) return res.status(400).json({ error: { code: 'VALIDATION', message: 'category is required' } });

    let visualDNA = {};
    let modestyRules = {};
    let traits = [];
    let role = 'supporting';
    let ageRange = '';
    let thumbnailUrl = '';

    if (characterId) {
      const char = await Character.findOne({ _id: characterId, userId: req.user._id });
      if (!char) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Character not found' } });

      visualDNA = char.visualDNA?.toObject ? char.visualDNA.toObject() : (char.visualDNA || {});
      modestyRules = char.modestyRules?.toObject ? char.modestyRules.toObject() : (char.modestyRules || {});
      traits = char.traits || [];
      role = char.role || 'supporting';
      ageRange = char.ageRange || '';
      thumbnailUrl = char.imageUrl || '';
    } else {
      visualDNA = req.body.visualDNA || {};
      modestyRules = req.body.modestyRules || {};
      traits = req.body.traits || [];
      role = req.body.role || 'supporting';
      ageRange = req.body.ageRange || '';
    }

    const template = await CharacterTemplate.create({
      name,
      description,
      category,
      thumbnailUrl,
      tags,
      isDefault: false,
      isPublic,
      createdBy: req.user._id,
      role,
      ageRange,
      traits,
      visualDNA,
      modestyRules,
    });

    // Mark the source character as published so the UI shows "Published" state
    if (characterId) {
      await Character.updateOne(
        { _id: characterId, userId: req.user._id },
        { publishedAsTemplateId: template._id }
      );
    }

    res.status(201).json(template);
  } catch (e) {
    next(e);
  }
});

// ─── DELETE /api/character-templates/:id ─────────────────────────────────────
router.delete('/:id', async (req, res, next) => {
  try {
    const tpl = await CharacterTemplate.findOne({ _id: req.params.id, createdBy: req.user._id });
    if (!tpl) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Template not found or not yours' } });

    await tpl.deleteOne();
    res.json({ message: 'Template deleted' });
  } catch (e) {
    next(e);
  }
});

export default router;
